import os
os.mkdir("3D")
os.chdir("3D")
print("Configuring 3D...")
print("Fetching Intro...")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/intro.mp4")
print("Fetching 3D Feature...")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/3D/glasses.mp4")
print("Fetching Odeon Mimics...")
os.mkdir("mimics")
os.chdir("mimics")
os.mkdir("Odeon")
os.chdir("Odeon")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Odeon/1.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Odeon/2.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Odeon/3.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Odeon/4.mp4")
print("Fetching Vue Mimics...")
os.chdir("..")
os.mkdir("Vue")
os.chdir("Vue")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Vue/1.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Vue/2.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Vue/3.mp4")
print("Fetching Cineworld Mimics...")
os.chdir("..")
os.mkdir("Cineworld")
os.chdir("Cineworld")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Cineworld/1.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Cineworld/2.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Cineworld/3.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Cineworld/4.mp4")
print("Fetching Adverts...")
os.chdir("..")
os.chdir("..")
os.mkdir("DCP")
os.chdir("DCP")
os.mkdir("adverts")
os.chdir("adverts")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/DCP/adverts/Digital_Cinema_Media.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/DCP/adverts/Pearl_And_Dean.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/DCP/adverts/Pearl_And_Dean_Old.mp4")
os.rename("Digital_Cinema_Media.mp4", "Digital_Cinema_Media.dca.mp4")
os.rename("Pearl_And_Dean.mp4", "Pearl_And_Dean.dca.mp4")
os.rename("Pearl_And_Dean_Old.mp4", "Pearl_And_Dean_Old.dca.mp4")
os.chdir("..")
os.chdir("..")
os.chdir("..")
os.mkdir("2D")
os.chdir("2D")
print("Configuring 2D...")
print("Fetching Intro...")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/intro.mp4")
print("Fetching 3D Feature...")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/3D/glasses.mp4")
print("Fetching Odeon Mimics...")
os.mkdir("mimics")
os.chdir("mimics")
os.mkdir("Odeon")
os.chdir("Odeon")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Odeon/1.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Odeon/2.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Odeon/3.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Odeon/4.mp4")
print("Fetching Vue Mimics...")
os.chdir("..")
os.mkdir("Vue")
os.chdir("Vue")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Vue/1.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Vue/2.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Vue/3.mp4")
print("Fetching Cineworld Mimics...")
os.chdir("..")
os.mkdir("Cineworld")
os.chdir("Cineworld")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Cineworld/1.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Cineworld/2.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Cineworld/3.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/mimics/Cineworld/4.mp4")
print("Fetching Adverts...")
os.chdir("..")
os.chdir("..")
os.mkdir("DCP")
os.chdir("DCP")
os.mkdir("adverts")
os.chdir("adverts")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/DCP/adverts/Digital_Cinema_Media.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/DCP/adverts/Pearl_And_Dean.mp4")
os.system("wget https://raw.githubusercontent.com/mrobraven/majestic-pi/master/majestic-pi/DCP/adverts/Pearl_And_Dean_Old.mp4")
os.rename("Digital_Cinema_Media.mp4", "Digital_Cinema_Media.dca.mp4")
os.rename("Pearl_And_Dean.mp4", "Pearl_And_Dean.dca.mp4")
os.rename("Pearl_And_Dean_Old.mp4", "Pearl_And_Dean_Old.dca.mp4")
print("Done!")
